apiVersion: v1
kind: Service
metadata:
  name: postgres-external
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
    - port: 5432          # Port inside the cluster
      targetPort: 5432    # Port inside the pod
      nodePort: 30432     # Port exposed on the node (custom, must be in range 30000-32767)